# Generated by Django 5.0.7 on 2024-08-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSet',
            fields=[
                ('movieID', models.IntegerField(primary_key=True, serialize=False)),
                ('imdbPictureURL', models.CharField(blank=True, max_length=300, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('AddressSpace1', models.CharField(blank=True, max_length=200, null=True)),
                ('AddressSpace2', models.CharField(blank=True, max_length=200, null=True)),
                ('directorID', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
