# Generated by Django 5.0.7 on 2024-08-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoScreen', '0002_alter_movieset_directorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieset',
            name='directorID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
