# Generated by Django 5.0.7 on 2024-08-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoScreen', '0005_rename_directorid_movie_directorname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='testrun',
        ),
    ]
