# Generated by Django 5.0.7 on 2024-08-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoScreen', '0008_remove_movie_director_remove_movie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbPictureURL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
