# Generated by Django 4.1 on 2024-08-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfoScreen', '0010_movie_rating_movie_tag1_movie_tag2_movie_tag3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
