# Generated by Django 4.1 on 2024-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorproject',
            fields=[
                ('directorID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('directorName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
