# Generated by Django 4.1 on 2024-08-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_directorproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actorproject',
            fields=[
                ('actorID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('actorName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Featuresproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.IntegerField()),
                ('actorID', models.CharField(max_length=100)),
                ('actorRankInMovie', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='featuresproject',
            constraint=models.UniqueConstraint(fields=('movieID', 'actorID'), name='unique_id1_id2'),
        ),
        migrations.AlterUniqueTogether(
            name='featuresproject',
            unique_together={('movieID', 'actorID')},
        ),
    ]
