# Generated by Django 4.1 on 2024-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_taggedasproject_tagproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchedbyproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='watchedbyproject',
            constraint=models.UniqueConstraint(fields=('movieID', 'userID'), name='unique_movieid1_userid2'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedbyproject',
            unique_together={('movieID', 'userID')},
        ),
    ]
